[package]
name = "rasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = "28.0"
wat = "1.220"
#anyhow = "1.0"
anyhow = { version = "1", default-features = false, features = ["std"] }
backtrace = "0.3.76"
color-backtrace = "0.6"
eyre = { version = "0.6" }
color-eyre = "0.6"
rasm-macros = { path = "rasm-macros" }
paste = "1.0"
