// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[derive(Clone)]
pub struct Person {
    pub name: _rt::String,
    pub age: u32,
    pub email: Option<_rt::String>,
}
impl ::core::fmt::Debug for Person {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Person")
            .field("name", &self.name)
            .field("age", &self.age)
            .field("email", &self.email)
            .finish()
    }
}
#[derive(Clone)]
pub struct Address {
    pub street: _rt::String,
    pub city: _rt::String,
    pub country: _rt::String,
    pub postal_code: _rt::String,
}
impl ::core::fmt::Debug for Address {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Address")
            .field("street", &self.street)
            .field("city", &self.city)
            .field("country", &self.country)
            .field("postal-code", &self.postal_code)
            .finish()
    }
}
#[derive(Clone)]
pub enum ResultCode {
    Success,
    NotFound,
    InvalidInput(_rt::String),
}
impl ::core::fmt::Debug for ResultCode {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            ResultCode::Success => f.debug_tuple("ResultCode::Success").finish(),
            ResultCode::NotFound => f.debug_tuple("ResultCode::NotFound").finish(),
            ResultCode::InvalidInput(e) => {
                f.debug_tuple("ResultCode::InvalidInput").field(e).finish()
            }
        }
    }
}
#[derive(Clone)]
pub struct Employee {
    pub person: Person,
    pub employee_id: u32,
    pub department: _rt::String,
    pub address: Address,
}
impl ::core::fmt::Debug for Employee {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Employee")
            .field("person", &self.person)
            .field("employee-id", &self.employee_id)
            .field("department", &self.department)
            .field("address", &self.address)
            .finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_greet_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::greet(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_greet<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_create_person_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::create_person(_rt::string_lift(bytes0), arg2 as u32);
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Person { name: name3, age: age3, email: email3 } = result1;
    let vec4 = (name3.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr2.add(0).cast::<*mut u8>() = ptr4.cast_mut();
    *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(age3);
    match email3 {
        Some(e) => {
            *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                as u8;
            let vec5 = (e.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr2.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *ptr2.add(4 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
                .cast_mut();
        }
        None => {
            *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                as u8;
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_create_person<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
    let l2 = i32::from(*arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    match l2 {
        0 => {}
        _ => {
            let l3 = *arg0
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l4 = *arg0.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_format_person_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
    arg3: i32,
    arg4: *mut u8,
    arg5: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result2 = T::format_person(Person {
        name: _rt::string_lift(bytes0),
        age: arg2 as u32,
        email: match arg3 {
            0 => None,
            1 => {
                let e = {
                    let len1 = arg5;
                    let bytes1 = _rt::Vec::from_raw_parts(arg4.cast(), len1, len1);
                    _rt::string_lift(bytes1)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    });
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec4 = (result2.into_bytes()).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_format_person<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_is_adult_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
    arg3: i32,
    arg4: *mut u8,
    arg5: usize,
) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result2 = T::is_adult(Person {
        name: _rt::string_lift(bytes0),
        age: arg2 as u32,
        email: match arg3 {
            0 => None,
            1 => {
                let e = {
                    let len1 = arg5;
                    let bytes1 = _rt::Vec::from_raw_parts(arg4.cast(), len1, len1);
                    _rt::string_lift(bytes1)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    });
    match result2 {
        true => 1,
        false => 0,
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_get_people_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::get_people();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec5 = result0;
    let len5 = vec5.len();
    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
        vec5.len() * (6 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result5 = if layout5.size() != 0 {
        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout5);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec5.into_iter().enumerate() {
        let base = result5.add(i * (6 * ::core::mem::size_of::<*const u8>()));
        {
            let Person { name: name2, age: age2, email: email2 } = e;
            let vec3 = (name2.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
            *base.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                age2,
            );
            match email2 {
                Some(e) => {
                    *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                        as u8;
                    let vec4 = (e.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *base.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *base
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                }
                None => {
                    *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                        as u8;
                }
            };
        }
    }
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr1.add(0).cast::<*mut u8>() = result5;
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_get_people<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base7 = l0;
    let len7 = l1;
    for i in 0..len7 {
        let base = base7.add(i * (6 * ::core::mem::size_of::<*const u8>()));
        {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l2, l3, 1);
            let l4 = i32::from(
                *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l4 {
                0 => {}
                _ => {
                    let l5 = *base
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l6 = *base
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l5, l6, 1);
                }
            }
        }
    }
    _rt::cabi_dealloc(
        base7,
        len7 * (6 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_find_person_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::find_person(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result1 {
        Some(e) => {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let Person { name: name3, age: age3, email: email3 } = e;
            let vec4 = (name3.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
            *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                age3,
            );
            match email3 {
                Some(e) => {
                    *ptr2.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32)
                        as u8;
                    let vec5 = (e.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr2.add(6 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr2
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                }
                None => {
                    *ptr2.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32)
                        as u8;
                }
            };
        }
        None => {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_find_person<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = i32::from(
                *arg0.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
            );
            match l3 {
                0 => {}
                _ => {
                    let l4 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                }
            }
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_validate_employee_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len2 = l1;
    let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
    let l3 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l4 = i32::from(*arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>());
    let l8 = *arg0.add(6 * ::core::mem::size_of::<*const u8>()).cast::<i32>();
    let l9 = *arg0.add(7 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l10 = *arg0.add(8 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len11 = l10;
    let bytes11 = _rt::Vec::from_raw_parts(l9.cast(), len11, len11);
    let l12 = *arg0.add(9 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l13 = *arg0.add(10 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len14 = l13;
    let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
    let l15 = *arg0.add(11 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l16 = *arg0.add(12 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len17 = l16;
    let bytes17 = _rt::Vec::from_raw_parts(l15.cast(), len17, len17);
    let l18 = *arg0.add(13 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l19 = *arg0.add(14 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len20 = l19;
    let bytes20 = _rt::Vec::from_raw_parts(l18.cast(), len20, len20);
    let l21 = *arg0.add(15 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l22 = *arg0.add(16 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let len23 = l22;
    let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);
    let result24 = T::validate_employee(Employee {
        person: Person {
            name: _rt::string_lift(bytes2),
            age: l3 as u32,
            email: match l4 {
                0 => None,
                1 => {
                    let e = {
                        let l5 = *arg0
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l6 = *arg0
                            .add(5 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let len7 = l6;
                        let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                        _rt::string_lift(bytes7)
                    };
                    Some(e)
                }
                _ => _rt::invalid_enum_discriminant(),
            },
        },
        employee_id: l8 as u32,
        department: _rt::string_lift(bytes11),
        address: Address {
            street: _rt::string_lift(bytes14),
            city: _rt::string_lift(bytes17),
            country: _rt::string_lift(bytes20),
            postal_code: _rt::string_lift(bytes23),
        },
    });
    _rt::cabi_dealloc(
        arg0,
        17 * ::core::mem::size_of::<*const u8>(),
        ::core::mem::size_of::<*const u8>(),
    );
    let ptr25 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result24 {
        ResultCode::Success => {
            *ptr25.add(0).cast::<u8>() = (0i32) as u8;
        }
        ResultCode::NotFound => {
            *ptr25.add(0).cast::<u8>() = (1i32) as u8;
        }
        ResultCode::InvalidInput(e) => {
            *ptr25.add(0).cast::<u8>() = (2i32) as u8;
            let vec26 = (e.into_bytes()).into_boxed_slice();
            let ptr26 = vec26.as_ptr().cast::<u8>();
            let len26 = vec26.len();
            ::core::mem::forget(vec26);
            *ptr25.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len26;
            *ptr25.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr26
                .cast_mut();
        }
    }
    ptr25
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_validate_employee<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {}
        1 => {}
        _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
    }
}
pub trait Guest {
    fn greet(name: _rt::String) -> _rt::String;
    fn create_person(name: _rt::String, age: u32) -> Person;
    fn format_person(p: Person) -> _rt::String;
    fn is_adult(p: Person) -> bool;
    fn get_people() -> _rt::Vec<Person>;
    fn find_person(name: _rt::String) -> Option<Person>;
    fn validate_employee(emp: Employee) -> ResultCode;
}
#[doc(hidden)]
macro_rules! __export_world_component_demo_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "greet")] unsafe extern "C" fn
        export_greet(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_greet_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_greet")] unsafe extern "C" fn _post_return_greet(arg0 :
        * mut u8,) { unsafe { $($path_to_types)*:: __post_return_greet::<$ty > (arg0) } }
        #[unsafe (export_name = "create-person")] unsafe extern "C" fn
        export_create_person(arg0 : * mut u8, arg1 : usize, arg2 : i32,) -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_create_person_cabi::<$ty > (arg0, arg1,
        arg2) } } #[unsafe (export_name = "cabi_post_create-person")] unsafe extern "C"
        fn _post_return_create_person(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_create_person::<$ty > (arg0) } } #[unsafe (export_name =
        "format-person")] unsafe extern "C" fn export_format_person(arg0 : * mut u8, arg1
        : usize, arg2 : i32, arg3 : i32, arg4 : * mut u8, arg5 : usize,) -> * mut u8 {
        unsafe { $($path_to_types)*:: _export_format_person_cabi::<$ty > (arg0, arg1,
        arg2, arg3, arg4, arg5) } } #[unsafe (export_name = "cabi_post_format-person")]
        unsafe extern "C" fn _post_return_format_person(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_format_person::<$ty > (arg0) } } #[unsafe
        (export_name = "is-adult")] unsafe extern "C" fn export_is_adult(arg0 : * mut u8,
        arg1 : usize, arg2 : i32, arg3 : i32, arg4 : * mut u8, arg5 : usize,) -> i32 {
        unsafe { $($path_to_types)*:: _export_is_adult_cabi::<$ty > (arg0, arg1, arg2,
        arg3, arg4, arg5) } } #[unsafe (export_name = "get-people")] unsafe extern "C" fn
        export_get_people() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_get_people_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_get-people")] unsafe extern "C" fn _post_return_get_people(arg0 : *
        mut u8,) { unsafe { $($path_to_types)*:: __post_return_get_people::<$ty > (arg0)
        } } #[unsafe (export_name = "find-person")] unsafe extern "C" fn
        export_find_person(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_find_person_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_find-person")] unsafe extern "C" fn
        _post_return_find_person(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_find_person::<$ty > (arg0) } } #[unsafe (export_name =
        "validate-employee")] unsafe extern "C" fn export_validate_employee(arg0 : * mut
        u8,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_validate_employee_cabi::<$ty > (arg0) } } #[unsafe (export_name =
        "cabi_post_validate-employee")] unsafe extern "C" fn
        _post_return_validate_employee(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_validate_employee::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_component_demo_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 7 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 7 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_component_demo_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_component_demo_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_component_demo_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:example:component:component-demo:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 569] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb4\x03\x01A\x02\x01\
A\x19\x01ks\x01r\x03\x04names\x03agey\x05email\0\x03\0\x06person\x03\0\x01\x01r\x04\
\x06streets\x04citys\x07countrys\x0bpostal-codes\x03\0\x07address\x03\0\x03\x01q\
\x03\x07success\0\0\x09not-found\0\0\x0dinvalid-input\x01s\0\x03\0\x0bresult-cod\
e\x03\0\x05\x01r\x04\x06person\x02\x0bemployee-idy\x0adepartments\x07address\x04\
\x03\0\x08employee\x03\0\x07\x01@\x01\x04names\0s\x04\0\x05greet\x01\x09\x01@\x02\
\x04names\x03agey\0\x02\x04\0\x0dcreate-person\x01\x0a\x01@\x01\x01p\x02\0s\x04\0\
\x0dformat-person\x01\x0b\x01@\x01\x01p\x02\0\x7f\x04\0\x08is-adult\x01\x0c\x01p\
\x02\x01@\0\0\x0d\x04\0\x0aget-people\x01\x0e\x01k\x02\x01@\x01\x04names\0\x0f\x04\
\0\x0bfind-person\x01\x10\x01@\x01\x03emp\x08\0\x06\x04\0\x11validate-employee\x01\
\x11\x04\0\x20example:component/component-demo\x04\0\x0b\x14\x01\0\x0ecomponent-\
demo\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\
\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
